### ISSUE TITLE
What is the scope of this repo?

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/sandbox#1]
When the dev hub is switched to docusaurus (soon), the landing page will be a react app that should live in the same https://github.com/substrate-developer-hub/docs repo.

Relevant context:
https://github.com/substrate-developer-hub/docs/issues/78
https://github.com/substrate-developer-hub/docs/issues/87

**Comment by shawntabrizi** [comment]
Just a sandbox. We should rename the `docs` repo to be `substrate-developer-hub.github.io`
